<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\rat-regions.png" />
    <None Remove="Assets\rat.png" />
    <None Remove="Assets\test_sprite.png" />
    <None Remove="Assets\test_sprite_channels.png" />
    <None Remove="Assets\test_sprite_mask.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Rat\rat-regions.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\rat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\test_sprite.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\test_sprite_channels.png" />
    <Resource Include="Assets\test_sprite_mask.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelRecolor.Core\PixelRecolor.Core.csproj" />
    <ProjectReference Include="..\PixelRecolor.Wpf\PixelRecolor.Wpf.csproj" />
  </ItemGroup>

</Project>
