<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\rat-regions.png" />
    <None Remove="Assets\rat.png" />
    <None Remove="Assets\Rat\Accessories\crown.png" />
    <None Remove="Assets\Rat\Accessories\santa.png" />
    <None Remove="Assets\Rat\Accessories\top_hat-2.png" />
    <None Remove="Assets\Rat\Accessories\top_hat.png" />
    <None Remove="Assets\Rat\Accessories\witch_hat.png" />
    <None Remove="Assets\Rat\Appearances\sir_rattington.json" />
    <None Remove="Assets\Rat\Palettes\black.json" />
    <None Remove="Assets\Rat\Palettes\silver.json" />
    <None Remove="Assets\Rat\Patterns\blaze.png" />
    <None Remove="Assets\Rat\Patterns\hooded.png" />
    <None Remove="Assets\Rat\Patterns\masked.png" />
    <None Remove="Assets\Rat\Patterns\spotted.png" />
    <None Remove="Assets\Rat\Patterns\variegated.png" />
    <None Remove="Assets\test_sprite.png" />
    <None Remove="Assets\test_sprite_channels.png" />
    <None Remove="Assets\test_sprite_mask.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Rat\Accessories\crown.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Accessories\santa.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Accessories\top_hat-2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Accessories\top_hat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Accessories\witch_hat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Appearances\sir_rattington.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Palettes\black.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Palettes\silver.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Patterns\blaze.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Patterns\hooded.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Patterns\masked.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Patterns\spotted.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\Patterns\variegated.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\rat-regions.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Rat\rat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\test_sprite.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\test_sprite_channels.png" />
    <Resource Include="Assets\test_sprite_mask.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelRecolor.Core\PixelRecolor.Core.csproj" />
    <ProjectReference Include="..\PixelRecolor.Wpf\PixelRecolor.Wpf.csproj" />
  </ItemGroup>

</Project>
